### PR TITLE
Feat/udp docker test

### PR DESCRIPTION
**Pull request by VendettaReborn**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

Currently, the docker test only covers TCP, but ignores UDP
So I added udp pingpong test and udp url_test(dns query) to cover it, and improved the coverage rate slightly

### 📝 Changelog

dev: support udp test in docker test
fix: fix datagram no `poll_flush` error in vmess & trojan & shadowsocks

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Changelog is provided or not needed

### coverage rate

the coverage rate is calculated by `cargo tarpaulin`.

- when we only have tcp test, the coverage rate under `proxy` directory is:  37%
- after, the coverage rate under `proxy` directory  is: 45%

### CODE REVIEW

**Comment by ibigbug** [comment]
@VendettaReborn were you able to run the wg tests locally?

**Review by ibigbug — APPROVED** [review]
need to figure out why wg is failing

**Comment by VendettaReborn** [comment]
> need to figure out why wg is failing

working on that

**Comment by VendettaReborn** [comment]
> @VendettaReborn were you able to run the wg tests locally?

yep, there is sth wrong with wg test, before this PR, the tcp test was ok.

**Pull request merged**
