### PR TITLE
add config reload api

### PR DESCRIPTION
**Pull request by ibigbug**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
#191 

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ibigbug** [comment]
@greenhat616

**Comment by greenhat616** [comment]
I tested it with nyanpasu dev, and server returned a 202(Accepted) error.

I think it should be blocking until the config refreshed, just as the meta does?
https://github.com/MetaCubeX/mihomo/blob/Alpha/hub/route/configs.go

**Comment by ibigbug** [comment]
is the config actually reloaded?

202 is not an error, and i think it shouldn't matter if this API is blocking/async. the other clash i think it returns 204 instead

**Comment by greenhat616** [comment]
> is the config actually reloaded?
> 
> 202 is not an error, and i think it shouldn't matter if this API is blocking/async. the other clash i think it returns 204 instead

Yes, I know it is intentional. It was caught by frontend request lib, such as `axios` or `fetch`. I can process it manually in next patch of nyanpasu. But users counld not get switch profiles until updates get released, though we have a core updater.

**Pull request merged**
