### PR TITLE
Format rust code with new style

### PR DESCRIPTION
**Pull request by SKTT1Ryze**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
Hello, everyone. I am about to start working on this project, and found something can be done to improve the development experience. One of them is the code style. Some lines in the current project exceed 85 characters, which will cause inconvenient to `vim` or `neovim` users, because they usually split the IDE into two windows, each one holds 85 characters at most. 

So this PR aims to change the code style by adding `rustfmt.toml` and re-formating the code with command `cargo fmt`.

### ☑️ Self-Check before Merge

Self-checked by executing `cargo build` and `cargo run` and the basic functions remain unchanged.

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by VendettaReborn** [comment]
nice

**Comment by ibigbug** [comment]
I'm a bit confused. Does vim not just display the lines as whatever the screen width is, why it's limited to 85*2 when splitted ?

**Comment by SKTT1Ryze** [comment]
> I'm a bit confused. Does vim not just display the lines as whatever the screen width is, why it's limited to 85*2 when splitted ?

It will display like this, which is ugly:
Screenshot 2024-06-29 at 12 14 40

But if we re-format it, it will like this:
Screenshot 2024-06-29 at 12 17 16

And this PR is just suggesting, if the maintainer think it's bad, we can close it. Thanks. :)

**Comment by ibigbug** [comment]
Thanks for explaining this. 

I'm not against it at all I also use vim(for python mostly, and i was with 79 line limit for PEP8 for many years, before switching to vscode). 

I'm more thinking if it's possible to make vim show wider lines as sow nowadays lots of people have wider screen sizes so we can fully utilize them.

**Comment by SKTT1Ryze** [comment]
> Thanks for explaining this.
> 
> I'm not against it at all I also use vim(for python mostly, and i was with 79 line limit for PEP8 for many years, before switching to vscode).
> 
> I'm more thinking if it's possible to make vim show wider lines as sow nowadays lots of people have wider screen sizes so we can fully utilize them.

I  got you. It seems like a difficult topic because different people have different conditions. In my case, I'm using `24-inch` Dell monitor and the font-size in my terminal was set to `16`, then I got the upper problem.

By the way, I found that there's another open source project written in Rust with 20k+ stars, [iced](https://github.com/iced-rs/iced), which is configured with `max_width = 20` in [rustfmt.toml](https://github.com/iced-rs/iced/blob/master/rustfmt.toml). So I think the number between `80` to `90` maybe a suitable choice.

**Review by ibigbug — APPROVED** [review]
Lgtm, thanks!

**Comment by Itsusinn** [comment]
Consider add
```toml
tab_spaces = 4
reorder_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
```
to rustfmt.toml

https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=tab_spaces#tab_spaces

https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=reorder_imports#reorder_imports

https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=reorder_impl_items#reorder_impl_items

https://rust-lang.github.io/rustfmt/?version=master&search=use_field_init_shorthand#use_field_init_shorthand

if We use nightly rustfmt, there will be more features can be enabled
```toml
unstable_features = true


version = "Two"

tab_spaces = 2

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true

wrap_comments = true
normalize_comments = true

reorder_impl_items = true
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
use_field_init_shorthand = true

format_strings = true
format_code_in_doc_comments = true
format_macro_matchers = true
```

**Comment by ibigbug** [comment]
Yeah we are using nightly now

**Comment by SKTT1Ryze** [comment]
> Consider add
> 
> ```toml
> tab_spaces = 4
> reorder_imports = true
> reorder_impl_items = true
> use_field_init_shorthand = true
> ```
> 
> to rustfmt.toml
> 
> https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=tab_spaces#tab_spaces
> 
> https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=reorder_imports#reorder_imports
> 
> https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=reorder_impl_items#reorder_impl_items
> 
> https://rust-lang.github.io/rustfmt/?version=master&search=use_field_init_shorthand#use_field_init_shorthand
> 
> IF We use nightly rustfmt (`cargo +nightly fmt`), there will be more features can be enabled
> 
> > As reference
> 
> ```toml
> unstable_features = true
> 
> 
> version = "Two"
> 
> tab_spaces = 4
> 
> group_imports = "StdExternalCrate"
> imports_granularity = "Crate"
> reorder_imports = true
> 
> wrap_comments = true
> normalize_comments = true
> 
> reorder_impl_items = true
> condense_wildcard_suffixes = true
> enum_discrim_align_threshold = 20
> use_field_init_shorthand = true
> 
> format_strings = true
> format_code_in_doc_comments = true
> format_macro_matchers = true
> ```

Done with new commit.

**Review by VendettaReborn — APPROVED** [review]

**Pull request merged**
