### PR TITLE
refactor(tun): use libtun

### PR DESCRIPTION
**Pull request by Itsusinn**
### 🤔 This is a ...

- [x] Refactoring

### 🔗 Related links
#208 

#362
#228
### Contents
- [x] Replace `netstack-lwip` with `netstack-smoltcp`
- [ ] Auto route

### CODE REVIEW

**Comment by ibigbug** [comment]
@VendettaReborn @cavivie thoughts?

seems this PR uses tun2 https://github.com/Itsusinn/libtun/blob/e8db4880bd5cca35930602222e7cfa549533f1f1/Cargo.toml#L8C8-L8C25

**Comment by cavivie** [comment]
I think we should migrate to tun2. Is the reason why we continue to use tun too much incompatible? We can abstract tun and netstack-lwip to libtun, and clash_lib does not directly depend on tun crate.

**Comment by VendettaReborn** [comment]
> I think we should migrate to tun2. Is the reason why we continue to use tun too much incompatible? We can abstract tun and netstack-lwip to libtun, and clash_lib does not directly depend on tun crate.

agreed

**Comment by ibigbug** [comment]
Yeah sounds good to me

**Comment by xmh0511** [comment]
We can use `tun2`, `ipstack`, and `net-route` to achieve the target.

**Pull request closed without merging**
