### PR TITLE
config api compatibility

### PR DESCRIPTION
**Pull request by ibigbug**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by greenhat616** [comment]
I tested it with nyanpasu. The api call is sucessfully. However, the backend seems not refresh successfully?
image
image

**Comment by ibigbug** [comment]
do you see any logs?

the data you posted seems to be from the subscription url and displayed by the client, not necessarly anything to do with the backend

**Comment by greenhat616** [comment]
Yes, I can see reloading info in log:
```
2023-12-26 22:11:04 INFO - [clash]:   2023-12-26T14:11:04.236512Z  INFO clash_lib: reloading config

2023-12-26 22:11:04 INFO - [clash]:     at clash_lib\src\lib.rs:305

2023-12-26 22:11:04 INFO - [clash]: 

2023-12-26 22:11:04 INFO - [clash]:   2023-12-26T14:11:04.256364Z DEBUG clash_lib: reloading dns resolver

2023-12-26 22:11:04 INFO - [clash]:     at clash_lib\src\lib.rs:314

2023-12-26 22:11:04 INFO - [clash]: 

2023-12-26 22:11:04 INFO - [clash]:   2023-12-26T14:11:04.256663Z DEBUG clash_lib: reloading mmdb

2023-12-26 22:11:04 INFO - [clash]:     at clash_lib\src\lib.rs:320

2023-12-26 22:11:04 INFO - [clash]: 

2023-12-26 22:11:04 INFO - [clash]:   2023-12-26T14:11:04.256695Z DEBUG clash_lib::common::mmdb: mmdb path: C:\Users\a632079\.config\clash-verge\Country.mmdb

2023-12-26 22:11:04 INFO - [clash]:     at clash_lib\src\common\mmdb.rs:26

2023-12-26 22:11:04 INFO - [clash]: 

2023-12-26 22:11:04 INFO - [clash]:   2023-12-26T14:11:04.260301Z DEBUG clash_lib: reloading cache store

2023-12-26 22:11:04 INFO - [clash]:     at clash_lib\src\lib.rs:330

2023-12-26 22:11:04 INFO - [clash]: 

2023-12-26 22:11:04 INFO - [clash]:   2023-12-26T14:11:04.260556Z DEBUG clash_lib: reloading outbound manager

2023-12-26 22:11:04 INFO - [clash]:     at clash_lib\src\lib.rs:339

2023-12-26 22:11:04 INFO - [clash]: 
```

That page is fetching data from GET `/proxies`, and seems config not be  applied to api endpoint.
image

**Comment by ibigbug** [comment]
ok i think it's a bug. let me take a look

**Comment by greenhat616** [comment]
Let me have a look later

**Comment by ibigbug** [comment]
The new listen port is :9090 does it not respond?

**Comment by greenhat616** [comment]
> The new listen port is :9090 does it not respond?

- no, remain old data yet.

**Comment by ibigbug** [comment]
@greenhat616 i think the backend is reloaded but somehow UI is not notified.

i tried to figure out the point when the UI refresh the proxies, but I can only find the auto refresh here https://github.com/keiko233/clash-nyanpasu/blob/main/src/components/proxy/use-render-list.ts#L28 

do you know if there's any other case the proxy list gets refreshed?

image

**Comment by greenhat616** [comment]
Confirmed. It seems SWR cache issue. Clash Nyanpasu use GET `/
providers/proxies` when core is `Clash Premium` or `Mihomo/ Mihomo Alpha`, which return a `chunked` encoding( it might break SWR cache). I supposed to draft a pr to fix this issue in Clash Nyanpasu.

**Review by greenhat616 — APPROVED** [review]

**Pull request merged**
